[package]
name = "curd-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.8", features = ["blocking"]  }
serde = {version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = "1.40.0"